#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBAProduction")]
	public partial class DataClassesSmallDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBuilding(Building instance);
    partial void UpdateBuilding(Building instance);
    partial void DeleteBuilding(Building instance);
    #endregion
		
		public DataClassesSmallDataContext() : 
				base(global::DowntownBoiseAssociation.Properties.Settings.Default.DBADevConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSmallDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSmallDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSmallDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSmallDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vw_MapAndDirectory_CSV> vw_MapAndDirectory_CSVs
		{
			get
			{
				return this.GetTable<vw_MapAndDirectory_CSV>();
			}
		}
		
		public System.Data.Linq.Table<Building> Buildings
		{
			get
			{
				return this.GetTable<Building>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_MapAndDirectory_CSV")]
	public partial class vw_MapAndDirectory_CSV
	{
		
		private string _CSVFile;
		
		public vw_MapAndDirectory_CSV()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSVFile", DbType="NVarChar(4000)")]
		public string CSVFile
		{
			get
			{
				return this._CSVFile;
			}
			set
			{
				if ((this._CSVFile != value))
				{
					this._CSVFile = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Building")]
	public partial class Building : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private System.Nullable<int> _BlockId;
		
		private string _ParcelNo;
		
		private System.Nullable<int> _Floors;
		
		private System.Nullable<int> _YearBuilt;
		
		private System.Nullable<int> _YearRenovated;
		
		private System.Nullable<int> _RentableSqFt;
		
		private System.Nullable<decimal> _AverageRent;
		
		private System.Nullable<int> _TotalSqFt;
		
		private System.Nullable<int> _UnbillableSqFt;
		
		private System.Guid _Guid;
		
		private System.Nullable<int> _AddressId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnBlockIdChanging(System.Nullable<int> value);
    partial void OnBlockIdChanged();
    partial void OnParcelNoChanging(string value);
    partial void OnParcelNoChanged();
    partial void OnFloorsChanging(System.Nullable<int> value);
    partial void OnFloorsChanged();
    partial void OnYearBuiltChanging(System.Nullable<int> value);
    partial void OnYearBuiltChanged();
    partial void OnYearRenovatedChanging(System.Nullable<int> value);
    partial void OnYearRenovatedChanged();
    partial void OnRentableSqFtChanging(System.Nullable<int> value);
    partial void OnRentableSqFtChanged();
    partial void OnAverageRentChanging(System.Nullable<decimal> value);
    partial void OnAverageRentChanged();
    partial void OnTotalSqFtChanging(System.Nullable<int> value);
    partial void OnTotalSqFtChanged();
    partial void OnUnbillableSqFtChanging(System.Nullable<int> value);
    partial void OnUnbillableSqFtChanged();
    partial void OnGuidChanging(System.Guid value);
    partial void OnGuidChanged();
    partial void OnAddressIdChanging(System.Nullable<int> value);
    partial void OnAddressIdChanged();
    #endregion
		
		public Building()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockId", DbType="Int")]
		public System.Nullable<int> BlockId
		{
			get
			{
				return this._BlockId;
			}
			set
			{
				if ((this._BlockId != value))
				{
					this.OnBlockIdChanging(value);
					this.SendPropertyChanging();
					this._BlockId = value;
					this.SendPropertyChanged("BlockId");
					this.OnBlockIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParcelNo", DbType="NVarChar(50)")]
		public string ParcelNo
		{
			get
			{
				return this._ParcelNo;
			}
			set
			{
				if ((this._ParcelNo != value))
				{
					this.OnParcelNoChanging(value);
					this.SendPropertyChanging();
					this._ParcelNo = value;
					this.SendPropertyChanged("ParcelNo");
					this.OnParcelNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Floors", DbType="Int")]
		public System.Nullable<int> Floors
		{
			get
			{
				return this._Floors;
			}
			set
			{
				if ((this._Floors != value))
				{
					this.OnFloorsChanging(value);
					this.SendPropertyChanging();
					this._Floors = value;
					this.SendPropertyChanged("Floors");
					this.OnFloorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearBuilt", DbType="Int")]
		public System.Nullable<int> YearBuilt
		{
			get
			{
				return this._YearBuilt;
			}
			set
			{
				if ((this._YearBuilt != value))
				{
					this.OnYearBuiltChanging(value);
					this.SendPropertyChanging();
					this._YearBuilt = value;
					this.SendPropertyChanged("YearBuilt");
					this.OnYearBuiltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearRenovated", DbType="Int")]
		public System.Nullable<int> YearRenovated
		{
			get
			{
				return this._YearRenovated;
			}
			set
			{
				if ((this._YearRenovated != value))
				{
					this.OnYearRenovatedChanging(value);
					this.SendPropertyChanging();
					this._YearRenovated = value;
					this.SendPropertyChanged("YearRenovated");
					this.OnYearRenovatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentableSqFt", DbType="Int")]
		public System.Nullable<int> RentableSqFt
		{
			get
			{
				return this._RentableSqFt;
			}
			set
			{
				if ((this._RentableSqFt != value))
				{
					this.OnRentableSqFtChanging(value);
					this.SendPropertyChanging();
					this._RentableSqFt = value;
					this.SendPropertyChanged("RentableSqFt");
					this.OnRentableSqFtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AverageRent", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> AverageRent
		{
			get
			{
				return this._AverageRent;
			}
			set
			{
				if ((this._AverageRent != value))
				{
					this.OnAverageRentChanging(value);
					this.SendPropertyChanging();
					this._AverageRent = value;
					this.SendPropertyChanged("AverageRent");
					this.OnAverageRentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSqFt", DbType="Int")]
		public System.Nullable<int> TotalSqFt
		{
			get
			{
				return this._TotalSqFt;
			}
			set
			{
				if ((this._TotalSqFt != value))
				{
					this.OnTotalSqFtChanging(value);
					this.SendPropertyChanging();
					this._TotalSqFt = value;
					this.SendPropertyChanged("TotalSqFt");
					this.OnTotalSqFtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnbillableSqFt", DbType="Int")]
		public System.Nullable<int> UnbillableSqFt
		{
			get
			{
				return this._UnbillableSqFt;
			}
			set
			{
				if ((this._UnbillableSqFt != value))
				{
					this.OnUnbillableSqFtChanging(value);
					this.SendPropertyChanging();
					this._UnbillableSqFt = value;
					this.SendPropertyChanged("UnbillableSqFt");
					this.OnUnbillableSqFtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guid", DbType="UniqueIdentifier NOT NULL", IsDbGenerated=true)]
		public System.Guid Guid
		{
			get
			{
				return this._Guid;
			}
			set
			{
				if ((this._Guid != value))
				{
					this.OnGuidChanging(value);
					this.SendPropertyChanging();
					this._Guid = value;
					this.SendPropertyChanged("Guid");
					this.OnGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressId", DbType="Int")]
		public System.Nullable<int> AddressId
		{
			get
			{
				return this._AddressId;
			}
			set
			{
				if ((this._AddressId != value))
				{
					this.OnAddressIdChanging(value);
					this.SendPropertyChanging();
					this._AddressId = value;
					this.SendPropertyChanged("AddressId");
					this.OnAddressIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
